server.port=8083
spring.application.name=conversion-service

# MySQL Database
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/conversion_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Service URLs
service.affiliate-service.url=http://affiliate-service:8081
service.campaign-service.url=http://campaign-service:8082